var CRM_CONST       = 
{ "speak"                : "no",
	"logo_txt"            : "NY BLÅ HIMMEL: ",
	"registered_txt"      : "Registrert:",
  "descAirstrip_txt"    : "Registrering av flystriper og skyer.",
  "descChemicals_txt"   : "Registrering av kjemikaler.",
  "descPH_txt"          : "Registrering av PH.",
  "descNotes_txt"       : "Registrering av kommentarer. ",
  "descLogin_txt"       : "Innlogging for NBH. ",
  "administration_txt"  : "Administrasjon",	
	"login_txt"           : "Logg inn",
	"logout_txt"          : "Logg ut",
	"signup_txt"          : "Registrer",
	"logo"                : "img/nbhLogo.png" ,
  "version"             : "ver 1.01",
	"version_claim"       : "versjon 1.01",
  "airstrip_txt"        : "Flystriper",
  "ph_txt"              : "PH",
  "chemicals_txt"       : "Kjemikaler",
  "changes_txt"         : "Endre",
  "user_more_txt"       : "Fylles ut av ",
  "choose_txt"          : "Velg",
  "status_txt"          : "Status",
  "new_txt"             : "Ny",
  
	"notes_txt"           : "Kommentar",
  "arkiv_txt"           : "Arkiv",
  "user_txt"            : "Bruker navn",
  "password_txt"        : "Passord",
 
  "registration_txt"    : "Observert:",
  "date_txt"            : "Dato",
  "clock_txt"           : "Klokkeslett", 
  "duration_txt"        : "Varighet:",
  "today_txt"           : "Dagens dato",  
  "durHours_txt"        : "Timer",
  "durMin_txt"          : "Minutter",
  
  "left_txt"            : "La igjen ",
  "airstrips_txt"       : "Flystripene er:",
  "normal_txt"          : "normale",
  "short_txt"           : "korte",
  "long_txt"            : "lange",
  "wide_txt"            : "vide",
  "dissipative_txt"     : "spredende",
  "lasting_txt"         : "varige",
  
  "cloud_txt"           : "lager kondens sky",
      
  "sim_a"               : "Antall flystriper fra andre fly",
  "moreAirNr_txt"       : "Antall flystriper fra andre fly",
  "sim_b"               : "Antall fly uten flystriper",
  "nStripeNr_txt"       : "Antall fly uten flystriper",
  
  "pictures_txt"        : "Bilder",
  "videos_txt"          : "Video",
  "forcast_txt"         : "Stemte været med værmeldinga:",
  "speed_txt"           : "Hastighet",
  "height_txt"          : "Høyde",
  "direction_txt"       : "Retning",
  "aircraft_txt"        : "Flytype",
  "airline_txt"         : "Flyselskap",
  "airtrafic_txt"       : "FlightRadar24",
  
  "initial_txt"         : [{"main" : "INITIALER"},{"comment" :"(Fornavn, Etternavn)"}],  
  "yes_txt"             : "Ja",
  "no_txt"              : "Nei",
  "doNotKnow_txt"       : "Vet ikke",
  "saveDesc_txt"        : "Lagrer registrering. Endringer gjøres senere med valget Arkiv",
  "id_txt"              : "Id",
  "info_txt"            : "Informasjon fra flightradar24",
  
  "localization_txt"    : "Lokalisering:",
  "posInfo_txt"         : "Tast inn addresse eller la GPS finne ut hvor du er ",
  "useAddress_txt"      : "Bruk addressen ",
  "address_txt"          :"Addresse", 
  "useGPS_txt"          : "Bruk GPS",
  "useLatLng_txt"       : "Bruk latitude og Longitude",
  "latitude_txt"        : "Latitude",
  "longitude"           : "Longiude",
  "save_txt"            : "Lagre ",
  "choose"              : null 
}; // end c_activity_report 	                      

module.exports=CRM_CONST;
