var CRM_CONST       = 
{ "speak"                : "en",
	"logo_txt"            : "NEW BLUE HEAVEN: ",
  "registered_txt"      : "Registered:", 
  "descAirstrip_txt"    : "Registration of airstrips and clouds.",
  "descChemicals_txt"   : "Registration of chemicals.",
  "descPH_txt"          : "Registration of PH.",
  "descNotes_txt"       : "Registration of comments. ",
  "descLogin_txt"       : "Login for NBH. ",
  "administration_txt"  : "Administation",	
	"login_txt"           : "Login",
	"logout_txt"          : "Logout",
	"signup_txt"          : "Registration",
	"logo"                : "img/nbhLogo.png" ,
  "version"             : "ver 1.01",
	"version_claim"       : "versjon 1.01",
  "airstrip_txt"        : "Airstrip",
  "ph_txt"              : "PH",
  "chemicals_txt"       : "Chemicals",
  "changes_txt"         : "Changes",
  "user_more_txt"       : "Filled out by ",
  "status_txt"          : "Status",
  "new_txt"             : "New",
  
	"notes_txt"           : "Comments",
  "arkiv_txt"           : "Arcive",
  "user_txt"            : "Username",
  "password_txt"        : "Password",
 
  "registration_txt"    : "Observation:",
  "date_txt"            : "Date",
  "clock_txt"           : "Time", 
  "duration_txt"        : "Duration:",
  "today_txt"           : "Current date",  
  "durHours_txt"      : "Hours",
  "durMin_txt"        : "Minutes",
  
  "left_txt"            : "Left behind ",
  "airstrips_txt"       : "Airstips are:",
  "short_txt"           : "normal",
  "long_txt"            : "longe",
  "wide_txt"            : "wide",
  "dissipative_txt"     : "dispersive",
  "lasting_txt"         : "lasting",
  
  "cloud_txt"           : "stock condensation cloud",
      
  "sim_a"               : "Number of airstrips from other aircraft",
  "moreAirNr_txt"       : "Number of airstrips from other aircraft",
  "sim_b"               : "Number of aircraft without airstrips",
  "noStripNr_txt"       : "Number of aircraft without airstrips",
  
  "pictures_txt"        : "Pictures",
  "videos_txt"          : "Videos",
  "forcast_txt"         : "Was the weather similar with forecast:",
  "speed_txt"           : "Speed",
  "height_txt"          : "Height",
  "direction_txt"       : "Direction",
  "aircraft_txt"        : "Aircraft",
  "airline_txt"         : "Airline",
  "airtrafic_txt"       : "FlightRadar24",
  
  "initial_txt"         : [{"main" : "initials"},{"comment" :"(First Name Last Name)"}],  
  "yes_txt"             : "Yes",
  "no_txt"              : "No",
  "doNotKnow_txt"       : "Do not know",
  "saveDesc_txt"            : "Store registration into database. It can be changed later.",
  "id_txt"              : "Id",
  "info_txt"            : "Information from flightradar24",
  
  "localization_txt"    : "Localization:",
  "posInfo_txt"         : "Enter the address or let GPS determine where you are ",
  "useAddress_txt"      : "Use address ",
  "address_txt"         :"Address", 
  "save_txt"            : "Save ",
  "useGPS_txt"          : "Use GPS", 
  "useLatLng_txt"       : "Use latitude and Longitude",
  "latitude_txt"        : "Latitude",
  "longitude"           : "Longiude"
  
}; // end c_activity_report 	                      

module.exports=CRM_CONST;
